[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ledmatrix"
version = "0.0.2"
authors = [
    { name = "jryuzaki"}, { name = "c0il" }
]
description = "UDP Realtime WLED Library"
readme = "README.md"
requires-python = ">=3.7"



